name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix: node-version:[16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

     - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        run: |
          git config --global user.email candicechu126@gmail.com
          git config --global user.name candicechu0126
          git remote set-url origin https://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@github.com/candicechu0126/portfolio.git
          npm run deploy
