name: Github Pages Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        uses: candicechu0126/portfolio
        with:
          folder: build
          branch: gh-pages
